
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("new", "Create users")) ?>
</div>

<?php echo $this->tag->form(array("search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search users</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="first_name">First Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("first_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_name">Last Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("last_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="bithday">Bithday</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("bithday", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">Email</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
